# Model arguments
model_name_or_path: /apdcephfs_qy3/share_1594716/yataobian/yang/pretrained/Qwen2.5-Math-7B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_usage: 0.1
dataset_name: /apdcephfs_qy3/share_1594716/yataobian/yang/dataset/NuminaMath-CoT
dataset_configs:
- train
# Num processes is less by 1 as vLLM is using 1 GPU
num_processes: 7
system_prompt: "Please reason step by step, and put your final answer within \\boxed{}."
# GRPO trainer config
bf16: true
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.4
do_eval: false
eval_strategy: "no"
eval_steps: 100
gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Qwen2.5-7B-EMPO-NM-COT-0328
hub_strategy: every_save
learning_rate: 1e-06
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: constant
max_prompt_length: 512
max_completion_length: 2048
max_steps: -1
num_generations: 5
num_train_epochs: 1
output_dir: /apdcephfs_qy3/share_1594716/yataobian/yang/output/data/Qwen2.5-7B-EMPO-NM-COT-0328
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 1
push_to_hub: false
reward_funcs:
- accuracy
- semantic_entropy_math
reward_weights:
- 0.0
- 1.0
save_strategy: "steps"
save_steps: 50
save_total_limit: 5
seed: 42
warmup_ratio: 0.00
beta: 0.0
