# Model arguments
model_name_or_path: pretrained/Qwen2.5-Math-1.5B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_usage: 1.0
dataset_name: RLHFlow/numia_prompt_dpo1
dataset_configs:
- train
# Num processes is less by 1 as vLLM is using 1 GPU
num_processes: 7
system_prompt: "Please reason step by step, and put your final answer within \\boxed{}."
# GRPO trainer config
bf16: true
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.7
do_eval: false
eval_strategy: "no"
eval_steps: 100
gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Qwen2.5-1.5B-EMPO-NM-COT-20K
hub_strategy: every_save
learning_rate: 1e-6
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: constant
max_prompt_length: 512
max_completion_length: 2048
max_steps: -1
num_generations: 7
num_train_epochs: 1
output_dir: Qwen2.5-1.5B-EMPO-NM-COT-20K
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 1
push_to_hub: false
reward_funcs:
- empo_math
reward_weights:
- 1.0
save_strategy: "steps"
save_steps: 50
save_total_limit: 5
seed: 42
warmup_ratio: 0.00
beta: 0.0
extract_answer: false