# Model arguments
model_name_or_path: pretrained/Qwen2.5-3B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: qingyangzhang/natural_reasoning_simple
dataset_train_split: train
# Num processes is less by 1 as vLLM is using 1 GPU
num_processes: 6
system_prompt: "Please reason step by step, and put your final answer within \\boxed{}."
# GRPO trainer config
bf16: true
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.5
do_eval: false
eval_strategy: "no"
eval_steps: 100
#temperature: 0.9
gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Qwen2.5-3B-GRPO-Natural-Reasoning
hub_strategy: every_save
learning_rate: 1e-06
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: constant
max_prompt_length: 1024
max_completion_length: 1024
max_steps: -1
num_generations: 12
num_train_epochs: 1
output_dir: Qwen2.5-3B-GRPO-Natural-Reasoning
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 1
push_to_hub: true
report_to:
- wandb
reward_funcs:
- general_accuracy
reward_weights:
- 1.0
save_strategy: "steps"
save_steps: 10
save_total_limit: 2
seed: 42
warmup_ratio: 0.0
dataset_usage: 1.0
beta: 0.0
print_outputs: true