# Model arguments
model_name_or_path: Qwen2.5-Math-1.5B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_usage: 1.0
dataset_name: /apdcephfs_qy3/share_1594716/yataobian/yang/dataset/NuminaMath-CoT
preprocessing_num_workers: 6

# SFT trainer config
bf16: true
do_eval: true
eval_strategy: "no"
eval_steps: 100
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Qwen2.5-Math-1.5B-SFT-NM-COT
hub_strategy: every_save
learning_rate: 2.0e-05
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
packing: true
max_seq_length: 9000
max_steps: -1
num_train_epochs: 1
output_dir: Qwen2.5-Math-1.5B-SFT-NM-COT
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 1
push_to_hub: true
report_to:
- wandb
save_strategy: "no"
seed: 42
warmup_ratio: 0.1